name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
      env:
        API_KEY: ${{ secrets.IYZICO_API_KEY }}
        SECRET_KEY: ${{ secrets.IYZICO_SECRET_KEY }}
